version: "3.9"

services:
  redis:
    image: redis
    restart: always

  webapp:
    restart: always
    build:
      context: ./django_app
    ports:
      - "8000:8000"
    command: ["python3", "./webapp/manage.py", "runserver", "0.0.0.0:8000"]

  worker:
    restart: always
    build:
      context: ./django_app
    volumes:
      - ./cats:/app/webapp/cats
    command: ['celery', '--workdir=./webapp', '-A', 'core', 'worker']