FROM python:3.8
RUN apt-get update -y
RUN apt-get upgrade -y

WORKDIR /app

COPY ./requirements.txt ./
RUN pip install -r requirements.txt
COPY ./webapp ./webapp

CMD ["python3", "webapp/manage.py", "runserver", "0.0.0.0:8000"]